# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-14 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='cep',
            field=models.CharField(db_index=True, default='00000000', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imovel',
            name='pais',
            field=models.CharField(db_index=True, default='00000000', max_length=200),
        ),
    ]
