# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-27 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0004_auto_20180614_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='imagem',
            field=models.ImageField(upload_to='aluguel/images/apts'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='slug',
            field=models.SlugField(),
        ),
    ]
