# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-27 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0007_auto_20180627_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='cidade',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='preco',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
    ]
