# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-14 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200)),
                ('imagem', models.ImageField(blank=True, upload_to='imoveis')),
                ('descricao', models.TextField(blank=True)),
                ('dono', models.TextField(blank=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero', models.PositiveIntegerField()),
                ('rua', models.CharField(db_index=True, max_length=200)),
                ('bairro', models.CharField(db_index=True, max_length=200)),
                ('cidade', models.CharField(db_index=True, max_length=200)),
                ('estado', models.CharField(db_index=True, max_length=200)),
                ('pais', models.CharField(db_index=True, max_length=200)),
                ('disponivel', models.BooleanField(default=True)),
                ('data_cadastramento', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('endereco', models.TextField(blank=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluguel.Categoria')),
            ],
            options={
                'ordering': ('-data_cadastramento',),
            },
        ),
    ]
